# Computational Social Science Project #2 

*Group number:* 

*Group members:*   

*Semester:* Fall 2021

Below we fill in some of the code you might use to answer some of the questions. Here are some additional resources for when you get stuck:
* Code and documentation provided in the course notebooks  
* [Markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to help with formatting the Jupyter notebook
* Try Googling any errors you get and consult Stack Overflow, etc. Someone has probably had your question before!
* Send me a pull request on GitHub flagging the syntax that's tripping you up

## 1. Introduction/Setup

#### a) Import relevant libraries
Add the other libraries you need for your code below and/or as you go.

In [2]:
# import libraries you might need here 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import os

# use random seed for consistent results 
np.random.seed(273)

#### b) Read in and inspect data frame 
Read in the data frame and look at some of its attributes.

In [3]:
os.getcwd()

'/Users/saa0726/Documents/CSS/Computational-Social-Science-Projects/project_2'

In [52]:
diabetes = pd.read_csv("Diabetes with Population Info by County 2017.csv", 
                       #CountyFips needs to be a string so leading 0 isn't dropped (this is only if you want to make choropleth map): 
                       dtype={"CountyFIPS": str})

In [5]:
diabetes

,County,State,CountyFIPS,Diabetes_Number,Obesity_Number,Physical_Inactivity_Number,sex and age_total population_65 years and over_sex ratio (males per 100 females),race_total population,race_total population_one race,race_total population_two or more races,...,sex and age_total population_21 years and over,sex and age_total population_62 years and over,sex and age_total population_65 years and over,sex and age_total population_18 years and over_1,sex and age_total population_18 years and over_male,sex and age_total population_18 years and over_female,sex and age_total population_18 years and over_sex ratio (males per 100 females),sex and age_total population_65 years and over_1,sex and age_total population_65 years and over_male,sex and age_total population_65 years and over_female
0,Autauga County,Alabama,01001,5178,13489,12525,76.5,55200,54170,1030,...,39614,9403,8050,41831,20054,21777,92.1,8050,3488,4562
1,Baldwin County,Alabama,01003,16707,48542,40024,86.6,208107,204535,3572,...,155502,49811,40665,162430,78104,84326,92.6,40665,18870,21795
2,Barbour County,Alabama,01005,3400,8009,5431,76.2,25782,25429,353,...,19394,5658,4634,20346,10923,9423,115.9,4634,2004,2630
3,Bibb County,Alabama,01007,2371,6534,5827,80.5,22527,22340,187,...,16864,4323,3661,17868,9578,8290,115.5,3661,1633,2028
4,Blount County,Alabama,01009,6282,14227,14365,79.7,57645,56710,935,...,42232,12400,10233,44177,21595,22582,95.6,10233,4540,5693
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,Sweetwater County,Wyoming,56037,2560,9362,7518,92.0,44117,43226,891,...,30491,6159,4721,32308,16800,15508,108.3,4721,2262,2459
3216,Teton County,Wyoming,56039,439,2051,2005,94.8,23059,22875,184,...,18169,3843,3135,18625,9619,9006,106.8,3135,1526,1609
3217,Uinta County,Wyoming,56041,1440,4925,3519,97.6,20609,19891,718,...,13939,3251,2498,14538,7280,7258,100.3,2498,1234,1264
3218,Washakie County,Wyoming,56043,637,1738,1708,89.0,8129,7791,338,...,5951,2041,1686,6187,3142,3045,103.2,1686,794,892
3219,Weston County,Wyoming,56045,601,2015,1383,90.6,7100,6956,144,...,5434,1770,1340,5595,2923,2672,109.4,1340,637,703

In [7]:
list(diabetes.columns)

['County',
 'State',
 'CountyFIPS',
 'Diabetes_Number',
 'Obesity_Number',
 'Physical_Inactivity_Number',
 'sex and age_total population_65 years and over_sex ratio (males per 100 females)',
 'race_total population',
 'race_total population_one race',
 'race_total population_two or more races',
 'race_total population_one race_1',
 'race_total population_one race_white',
 'race_total population_one race_black or african american',
 'race_total population_one race_american indian and alaska native',
 'race_total population_one race_american indian and alaska native_cherokee tribal grouping',
 'race_total population_one race_american indian and alaska native_chippewa tribal grouping',
 'race_total population_one race_american indian and alaska native_navajo tribal grouping',
 'race_total population_one race_american indian and alaska native_sioux tribal grouping',
 'race_total population_one race_asian',
 'race_total population_one race_asian_asian indian',
 'race_total population_one race_asian_chinese',
 'race_total population_one race_asian_filipino',
 'race_total population_one race_asian_japanese',
 'race_total population_one race_asian_korean',
 'race_total population_one race_asian_vietnamese',
 'race_total population_one race_asian_other asian',
 'race_total population_one race_native hawaiian and other pacific islander',
 'race_total population_one race_native hawaiian and other pacific islander_native hawaiian',
 'race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro',
 'race_total population_one race_native hawaiian and other pacific islander_samoan',
 'race_total population_one race_native hawaiian and other pacific islander_other pacific islander',
 'race_total population_one race_some other race',
 'race_total population_two or more races_1',
 'race_total population_two or more races_white and black or african american',
 'race_total population_two or more races_white and american indian and alaska native',
 'race_total population_two or more races_white and asian',
 'race_total population_two or more races_black or african american and american indian and alaska native',
 'race alone or in combination with one or more other races_total population',
 'race alone or in combination with one or more other races_total population_white',
 'race alone or in combination with one or more other races_total population_black or african american',
 'race alone or in combination with one or more other races_total population_american indian and alaska native',
 'race alone or in combination with one or more other races_total population_asian',
 'race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander',
 'race alone or in combination with one or more other races_total population_some other race',
 'hispanic or latino and race_total population',
 'hispanic or latino and race_total population_hispanic or latino (of any race)',
 'hispanic or latino and race_total population_hispanic or latino (of any race)_mexican',
 'hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican',
 'hispanic or latino and race_total population_hispanic or latino (of any race)_cuban',
 'hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino',
 'hispanic or latino and race_total population_not hispanic or latino',
 'hispanic or latino and race_total population_not hispanic or latino_white alone',
 'hispanic or latino and race_total population_not hispanic or latino_black or african american alone',
 'hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone',
 'hispanic or latino and race_total population_not hispanic or latino_asian alone',
 'hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone',
 'hispanic or latino and race_total population_not hispanic or latino_some other race alone',
 'hispanic or latino and race_total population_not hispanic or latino_two or more races',
 'hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race',
 'hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race -  and three or more races',
 'total housing units',
 'citizen -  voting age population_citizen -  18 and over population',
 'citizen -  voting age population_citizen -  18 and over population_male',
 'citizen -  voting age population_citizen -  18 and over population_female',
 'sex and age_total population',
 'sex and age_total population_male',
 'sex and age_total population_female',
 'sex and age_total population_sex ratio (males per 100 females)',
 'sex and age_total population_under 5 years',
 'sex and age_total population_5 to 9 years',
 'sex and age_total population_10 to 14 years',
 'sex and age_total population_15 to 19 years',
 'sex and age_total population_20 to 24 years',
 'sex and age_total population_25 to 34 years',
 'sex and age_total population_35 to 44 years',
 'sex and age_total population_45 to 54 years',
 'sex and age_total population_55 to 59 years',
 'sex and age_total population_60 to 64 years',
 'sex and age_total population_65 to 74 years',
 'sex and age_total population_75 to 84 years',
 'sex and age_total population_85 years and over',
 'sex and age_total population_median age (years)',
 'sex and age_total population_under 18 years',
 'sex and age_total population_16 years and over',
 'sex and age_total population_18 years and over',
 'sex and age_total population_21 years and over',
 'sex and age_total population_62 years and over',
 'sex and age_total population_65 years and over',
 'sex and age_total population_18 years and over_1',
 'sex and age_total population_18 years and over_male',
 'sex and age_total population_18 years and over_female',
 'sex and age_total population_18 years and over_sex ratio (males per 100 females)',
 'sex and age_total population_65 years and over_1',
 'sex and age_total population_65 years and over_male',
 'sex and age_total population_65 years and over_female']

In [9]:
# look at the dimensions of the diabetes data frame
print('shape: ', diabetes.shape)

shape:  (3220, 95)

In [11]:
pd.set_option('display.max_rows', 100) # tells pandas how many rows to display when printing so results don't get truncated

# look at the data types for each column in diabetes df 
print('data types:', diabetes.dtypes)

data types: County                                                                                                                                                   object
State                                                                                                                                                    object
CountyFIPS                                                                                                                                               object
Diabetes_Number                                                                                                                                          object
Obesity_Number                                                                                                                                           object
Physical_Inactivity_Number                                                                                                                               object
sex and age_total population_65 years and over_sex ratio (males per 100 females)                                                                         object
race_total population                                                                                                                                     int64
race_total population_one race                                                                                                                            int64
race_total population_two or more races                                                                                                                   int64
race_total population_one race_1                                                                                                                          int64
race_total population_one race_white                                                                                                                      int64
race_total population_one race_black or african american                                                                                                  int64
race_total population_one race_american indian and alaska native                                                                                          int64
race_total population_one race_american indian and alaska native_cherokee tribal grouping                                                                 int64
race_total population_one race_american indian and alaska native_chippewa tribal grouping                                                                 int64
race_total population_one race_american indian and alaska native_navajo tribal grouping                                                                   int64
race_total population_one race_american indian and alaska native_sioux tribal grouping                                                                    int64
race_total population_one race_asian                                                                                                                      int64
race_total population_one race_asian_asian indian                                                                                                         int64
race_total population_one race_asian_chinese                                                                                                              int64
race_total population_one race_asian_filipino                                                                                                             int64
race_total population_one race_asian_japanese                                                                                                             int64
race_total population_one race_asian_korean                                                                                                               int64
race_total population_one race_asian_vietnamese                                                                                                           int64
race_total population_one race_asian_other asian                                                                                                          int64
race_total population_one race_native hawaiian and other pacific islander                                                                                 int64
race_total population_one race_native hawaiian and other pacific islander_native hawaiian                                                                 int64
race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro                                                           int64
race_total population_one race_native hawaiian and other pacific islander_samoan                                                                          int64
race_total population_one race_native hawaiian and other pacific islander_other pacific islander                                                          int64
race_total population_one race_some other race                                                                                                            int64
race_total population_two or more races_1                                                                                                                 int64
race_total population_two or more races_white and black or african american                                                                               int64
race_total population_two or more races_white and american indian and alaska native                                                                       int64
race_total population_two or more races_white and asian                                                                                                   int64
race_total population_two or more races_black or african american and american indian and alaska native                                                   int64
race alone or in combination with one or more other races_total population                                                                                int64
race alone or in combination with one or more other races_total population_white                                                                          int64
race alone or in combination with one or more other races_total population_black or african american                                                      int64
race alone or in combination with one or more other races_total population_american indian and alaska native                                              int64
race alone or in combination with one or more other races_total population_asian                                                                          int64
race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander                                     int64
race alone or in combination with one or more other races_total population_some other race                                                                int64
hispanic or latino and race_total population                                                                                                              int64
hispanic or latino and race_total population_hispanic or latino (of any race)                                                                             int64
hispanic or latino and race_total population_hispanic or latino (of any race)_mexican                                                                     int64
hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican                                                                int64
hispanic or latino and race_total population_hispanic or latino (of any race)_cuban                                                                       int64
hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino                                                    int64
hispanic or latino and race_total population_not hispanic or latino                                                                                       int64
hispanic or latino and race_total population_not hispanic or latino_white alone                                                                           int64
hispanic or latino and race_total population_not hispanic or latino_black or african american alone                                                       int64
hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone                                               int64
hispanic or latino and race_total population_not hispanic or latino_asian alone                                                                           int64
hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone                                      int64
hispanic or latino and race_total population_not hispanic or latino_some other race alone                                                                 int64
hispanic or latino and race_total population_not hispanic or latino_two or more races                                                                     int64
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race                                 int64
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race -  and three or more races      int64
total housing units                                                                                                                                       int64
citizen -  voting age population_citizen -  18 and over population                                                                                        int64
citizen -  voting age population_citizen -  18 and over population_male                                                                                   int64
citizen -  voting age population_citizen -  18 and over population_female                                                                                 int64
sex and age_total population                                                                                                                              int64
sex and age_total population_male                                                                                                                         int64
sex and age_total population_female                                                                                                                       int64
sex and age_total population_sex ratio (males per 100 females)                                                                                          float64
sex and age_total population_under 5 years                                                                                                                int64
sex and age_total population_5 to 9 years                                                                                                                 int64
sex and age_total population_10 to 14 years                                                                                                               int64
sex and age_total population_15 to 19 years                                                                                                               int64
sex and age_total population_20 to 24 years                                                                                                               int64
sex and age_total population_25 to 34 years                                                                                                               int64
sex and age_total population_35 to 44 years                                                                                                               int64
sex and age_total population_45 to 54 years                                                                                                               int64
sex and age_total population_55 to 59 years                                                                                                               int64
sex and age_total population_60 to 64 years                                                                                                               int64
sex and age_total population_65 to 74 years                                                                                                               int64
sex and age_total population_75 to 84 years                                                                                                               int64
sex and age_total population_85 years and over                                                                                                            int64
sex and age_total population_median age (years)                                                                                                         float64
sex and age_total population_under 18 years                                                                                                               int64
sex and age_total population_16 years and over                                                                                                            int64
sex and age_total population_18 years and over                                                                                                            int64
sex and age_total population_21 years and over                                                                                                            int64
sex and age_total population_62 years and over                                                                                                            int64
sex and age_total population_65 years and over                                                                                                            int64
sex and age_total population_18 years and over_1                                                                                                          int64
sex and age_total population_18 years and over_male                                                                                                       int64
sex and age_total population_18 years and over_female                                                                                                     int64
sex and age_total population_18 years and over_sex ratio (males per 100 females)                                                                        float64
sex and age_total population_65 years and over_1                                                                                                          int64
sex and age_total population_65 years and over_male                                                                                                       int64
sex and age_total population_65 years and over_female                                                                                                     int64
dtype: object

Immediately, we see that some of the features that should be numeric (e.g., Diabetes_Number, Obesity_Number,  and Physical_Inactivity_Number) are not. We can check to see what the non-numeric values are in a column where we are expecting numeric information with a combination of `str.isnumeric()` and `unique()`.

In [24]:
# Return rows where the column "Diabetes_Number" is non-numeric and get the unique values of these rows
# the "~" below in front of diabetes negates the str.isnumeric() so it only takes non-numeric values
print(diabetes[~diabetes["Diabetes_Number"].str.isnumeric()]["Diabetes_Number"].unique())

2751    Suppressed
Name: Diabetes_Number, dtype: object

In [28]:
diabetes[~diabetes["Diabetes_Number"].str.isnumeric()]

,County,State,CountyFIPS,Diabetes_Number,Obesity_Number,Physical_Inactivity_Number,sex and age_total population_65 years and over_sex ratio (males per 100 females),race_total population,race_total population_one race,race_total population_two or more races,...,sex and age_total population_21 years and over,sex and age_total population_62 years and over,sex and age_total population_65 years and over,sex and age_total population_18 years and over_1,sex and age_total population_18 years and over_male,sex and age_total population_18 years and over_female,sex and age_total population_18 years and over_sex ratio (males per 100 females),sex and age_total population_65 years and over_1,sex and age_total population_65 years and over_male,sex and age_total population_65 years and over_female
2751,Loving County,Texas,48301,Suppressed,26,21,150.0,102,102,0,...,78,31,25,78,47,31,151.6,25,15,10

In [53]:
# Now do the same as above, but for "Obesity_Number" :
print(diabetes[~diabetes["Obesity_Number"].str.isnumeric()]["Obesity_Number"].unique())

['No Data']

In [33]:
diabetes['sex and age_total population_65 years and over_sex ratio (males per 100 females)']

0       76.5
1       86.6
2       76.2
3       80.5
4       79.7
        ...
3215    92.0
3216    94.8
3217    97.6
3218    89.0
3219    90.6
Name: sex and age_total population_65 years and over_sex ratio (males per 100 females), Length: 3220, dtype: object

The values contained in the two columns above making them objects (rather than integers) appear to be strings like "No Data" and "Suppressed." Let's drop those rows in the next section, and also recode Physical_Inactivity_Number to be an integer.

#### c. Recode variables

Convert 'Diabetes_Number', 'Obesity_Number', and 'Physical_Inactivity_Number' to integers below so we can use them in our analysis. Also fill in the object type we want to recode 'sex and age_total population_65 years and over_sex ratio (males per 100 females)' to.

In [59]:
# Diabetes
# keep only useful info about our target feature, i.e., where diabetes_number not = 'Suppressed'
diabetes = diabetes[diabetes['Diabetes_Number']!="Suppressed"]  # note that the inside reference to the diabetes df identifies the column, and the outer calls specific rows according to a condition

In [60]:
assert not (diabetes['Diabetes_Number'] == 'Suppressed').any()

In [68]:
diabetes = diabetes[diabetes['Obesity_Number']!='No Data']

In [71]:
diabetes[['Diabetes_Number', 'Obesity_Number', 'Physical_Inactivity_Number']] = diabetes[['Diabetes_Number', 'Obesity_Number', 'Physical_Inactivity_Number']].astype(int)

In [72]:
diabetes[['Diabetes_Number', 'Obesity_Number', 'Physical_Inactivity_Number']].dtypes

Diabetes_Number               int64
Obesity_Number                int64
Physical_Inactivity_Number    int64
dtype: object

In [77]:
# 65+ sex ratio had one "-" in it so let's drop that row first
diabetes = diabetes[diabetes['sex and age_total population_65 years and over_sex ratio (males per 100 females)']!= "-"]

In [75]:
diabetes['sex and age_total population_65 years and over_sex ratio (males per 100 females)'].head()

0    76.5
1    86.6
2    76.2
3    80.5
4    79.7
Name: sex and age_total population_65 years and over_sex ratio (males per 100 females), dtype: object

In [78]:
# change to numeric (specifically, integer or float?) from string (because originally included the "-" )
diabetes['sex and age_total population_65 years and over_sex ratio (males per 100 females)'] = diabetes['sex and age_total population_65 years and over_sex ratio (males per 100 females)'].astype(float)

We should probably scale our count variables to be proportional to county population. We create the list 'rc_cols' to select all the features we want to rescale, and then use the `.div()` method to avoid typing out every single column we want to recode.

In [79]:
# select count variables to rc to percentages; make sure we leave out ratios and our population variable b/c these don't make sense to scale by population
rc_cols = [col for col in diabetes.columns if col not in ['County', 'State', 'CountyFIPS', 
                                                        'sex and age_total population_65 years and over_sex ratio (males per 100 females)', 'sex and age_total population_sex ratio (males per 100 females)', 'sex and age_total population_18 years and over_sex ratio (males per 100 females)',  
                                                        'race_total population']]

In [80]:
rc_cols

['Diabetes_Number',
 'Obesity_Number',
 'Physical_Inactivity_Number',
 'race_total population_one race',
 'race_total population_two or more races',
 'race_total population_one race_1',
 'race_total population_one race_white',
 'race_total population_one race_black or african american',
 'race_total population_one race_american indian and alaska native',
 'race_total population_one race_american indian and alaska native_cherokee tribal grouping',
 'race_total population_one race_american indian and alaska native_chippewa tribal grouping',
 'race_total population_one race_american indian and alaska native_navajo tribal grouping',
 'race_total population_one race_american indian and alaska native_sioux tribal grouping',
 'race_total population_one race_asian',
 'race_total population_one race_asian_asian indian',
 'race_total population_one race_asian_chinese',
 'race_total population_one race_asian_filipino',
 'race_total population_one race_asian_japanese',
 'race_total population_one race_asian_korean',
 'race_total population_one race_asian_vietnamese',
 'race_total population_one race_asian_other asian',
 'race_total population_one race_native hawaiian and other pacific islander',
 'race_total population_one race_native hawaiian and other pacific islander_native hawaiian',
 'race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro',
 'race_total population_one race_native hawaiian and other pacific islander_samoan',
 'race_total population_one race_native hawaiian and other pacific islander_other pacific islander',
 'race_total population_one race_some other race',
 'race_total population_two or more races_1',
 'race_total population_two or more races_white and black or african american',
 'race_total population_two or more races_white and american indian and alaska native',
 'race_total population_two or more races_white and asian',
 'race_total population_two or more races_black or african american and american indian and alaska native',
 'race alone or in combination with one or more other races_total population',
 'race alone or in combination with one or more other races_total population_white',
 'race alone or in combination with one or more other races_total population_black or african american',
 'race alone or in combination with one or more other races_total population_american indian and alaska native',
 'race alone or in combination with one or more other races_total population_asian',
 'race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander',
 'race alone or in combination with one or more other races_total population_some other race',
 'hispanic or latino and race_total population',
 'hispanic or latino and race_total population_hispanic or latino (of any race)',
 'hispanic or latino and race_total population_hispanic or latino (of any race)_mexican',
 'hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican',
 'hispanic or latino and race_total population_hispanic or latino (of any race)_cuban',
 'hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino',
 'hispanic or latino and race_total population_not hispanic or latino',
 'hispanic or latino and race_total population_not hispanic or latino_white alone',
 'hispanic or latino and race_total population_not hispanic or latino_black or african american alone',
 'hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone',
 'hispanic or latino and race_total population_not hispanic or latino_asian alone',
 'hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone',
 'hispanic or latino and race_total population_not hispanic or latino_some other race alone',
 'hispanic or latino and race_total population_not hispanic or latino_two or more races',
 'hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race',
 'hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race -  and three or more races',
 'total housing units',
 'citizen -  voting age population_citizen -  18 and over population',
 'citizen -  voting age population_citizen -  18 and over population_male',
 'citizen -  voting age population_citizen -  18 and over population_female',
 'sex and age_total population',
 'sex and age_total population_male',
 'sex and age_total population_female',
 'sex and age_total population_under 5 years',
 'sex and age_total population_5 to 9 years',
 'sex and age_total population_10 to 14 years',
 'sex and age_total population_15 to 19 years',
 'sex and age_total population_20 to 24 years',
 'sex and age_total population_25 to 34 years',
 'sex and age_total population_35 to 44 years',
 'sex and age_total population_45 to 54 years',
 'sex and age_total population_55 to 59 years',
 'sex and age_total population_60 to 64 years',
 'sex and age_total population_65 to 74 years',
 'sex and age_total population_75 to 84 years',
 'sex and age_total population_85 years and over',
 'sex and age_total population_median age (years)',
 'sex and age_total population_under 18 years',
 'sex and age_total population_16 years and over',
 'sex and age_total population_18 years and over',
 'sex and age_total population_21 years and over',
 'sex and age_total population_62 years and over',
 'sex and age_total population_65 years and over',
 'sex and age_total population_18 years and over_1',
 'sex and age_total population_18 years and over_male',
 'sex and age_total population_18 years and over_female',
 'sex and age_total population_65 years and over_1',
 'sex and age_total population_65 years and over_male',
 'sex and age_total population_65 years and over_female']

In [81]:
diabetes[rc_cols] = diabetes[rc_cols].apply(pd.to_numeric, errors='coerce') # recode all selected columns to numeric

In [82]:
# divide all columns but those listed above by total population to calculate rates
diabetes[rc_cols] = diabetes[rc_cols].div(diabetes['race_total population'], axis=0)

In [83]:
diabetes

,County,State,CountyFIPS,Diabetes_Number,Obesity_Number,Physical_Inactivity_Number,sex and age_total population_65 years and over_sex ratio (males per 100 females),race_total population,race_total population_one race,race_total population_two or more races,...,sex and age_total population_21 years and over,sex and age_total population_62 years and over,sex and age_total population_65 years and over,sex and age_total population_18 years and over_1,sex and age_total population_18 years and over_male,sex and age_total population_18 years and over_female,sex and age_total population_18 years and over_sex ratio (males per 100 females),sex and age_total population_65 years and over_1,sex and age_total population_65 years and over_male,sex and age_total population_65 years and over_female
0,Autauga County,Alabama,01001,0.093804,0.244366,0.226902,76.5,55200,0.981341,0.018659,...,0.717645,0.170344,0.145833,0.757808,0.363297,0.394511,92.1,0.145833,0.063188,0.082645
1,Baldwin County,Alabama,01003,0.080281,0.233255,0.192324,86.6,208107,0.982836,0.017164,...,0.747221,0.239353,0.195404,0.780512,0.375307,0.405205,92.6,0.195404,0.090675,0.104730
2,Barbour County,Alabama,01005,0.131875,0.310643,0.210651,76.2,25782,0.986308,0.013692,...,0.752230,0.219455,0.179738,0.789155,0.423668,0.365488,115.9,0.179738,0.077729,0.102009
3,Bibb County,Alabama,01007,0.105251,0.290052,0.258667,80.5,22527,0.991699,0.008301,...,0.748613,0.191903,0.162516,0.793182,0.425179,0.368003,115.5,0.162516,0.072491,0.090025
4,Blount County,Alabama,01009,0.108977,0.246804,0.249198,79.7,57645,0.983780,0.016220,...,0.732622,0.215110,0.177518,0.766363,0.374621,0.391743,95.6,0.177518,0.078758,0.098760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,Sweetwater County,Wyoming,56037,0.058028,0.212208,0.170410,92.0,44117,0.979804,0.020196,...,0.691139,0.139606,0.107011,0.732325,0.380806,0.351520,108.3,0.107011,0.051273,0.055738
3216,Teton County,Wyoming,56039,0.019038,0.088946,0.086951,94.8,23059,0.992020,0.007980,...,0.787935,0.166659,0.135956,0.807711,0.417147,0.390563,106.8,0.135956,0.066178,0.069778
3217,Uinta County,Wyoming,56041,0.069872,0.238973,0.170751,97.6,20609,0.965161,0.034839,...,0.676355,0.157747,0.121209,0.705420,0.353244,0.352176,100.3,0.121209,0.059877,0.061332
3218,Washakie County,Wyoming,56043,0.078361,0.213802,0.210112,89.0,8129,0.958420,0.041580,...,0.732070,0.251076,0.207406,0.761102,0.386517,0.374585,103.2,0.207406,0.097675,0.109731
3219,Weston County,Wyoming,56045,0.084648,0.283803,0.194789,90.6,7100,0.979718,0.020282,...,0.765352,0.249296,0.188732,0.788028,0.411690,0.376338,109.4,0.188732,0.089718,0.099014

Let's check our work. Are all rates bounded by 0 and 1 as expected?

In [84]:
pd.set_option('display.max_columns', None)
# inspect recoded values
diabetes_summary = diabetes.describe().transpose() # note we use the transpose method rather than .T because this object is not a numpy array
diabetes_summary

,count,mean,std,min,25%,50%,75%,max
Diabetes_Number,3112.0,0.092857,0.028097,0.019038,0.072169,0.089291,0.110175,2.242079e-01
Obesity_Number,3112.0,0.251666,0.044323,0.088946,0.223436,0.252390,0.280113,4.767883e-01
Physical_Inactivity_Number,3112.0,0.200861,0.044511,0.064949,0.170128,0.199036,0.231041,3.922853e-01
sex and age_total population_65 years and over_sex ratio (males per 100 females),3112.0,84.275643,10.347722,34.700000,78.300000,82.600000,88.400000,2.200000e+02
race_total population,3112.0,103682.624036,331362.542093,228.000000,11226.750000,26137.500000,68477.250000,1.009805e+07
race_total population_one race,3112.0,0.976059,0.019379,0.713126,0.971038,0.980119,0.986630,1.000000e+00
race_total population_two or more races,3112.0,0.023941,0.019379,0.000000,0.013370,0.019881,0.028962,2.868743e-01
race_total population_one race_1,3112.0,0.976059,0.019379,0.713126,0.971038,0.980119,0.986630,1.000000e+00
race_total population_one race_white,3112.0,0.831107,0.167534,0.038912,0.767171,0.896086,0.950193,1.000000e+00
race_total population_one race_black or african american,3112.0,0.090215,0.144287,0.000000,0.006815,0.022927,0.101805,8.741228e-01
race_total population_one race_american indian and alaska native,3112.0,0.019398,0.076536,0.000000,0.001722,0.003499,0.008392,9.247994e-01
race_total population_one race_american indian and alaska native_cherokee tribal grouping,3112.0,0.001791,0.013060,0.000000,0.000000,0.000249,0.000941,4.096685e-01
race_total population_one race_american indian and alaska native_chippewa tribal grouping,3112.0,0.001338,0.016379,0.000000,0.000000,0.000000,0.000071,7.264946e-01
race_total population_one race_american indian and alaska native_navajo tribal grouping,3112.0,0.001229,0.020968,0.000000,0.000000,0.000000,0.000000,7.054752e-01
race_total population_one race_american indian and alaska native_sioux tribal grouping,3112.0,0.003315,0.039049,0.000000,0.000000,0.000000,0.000137,8.339016e-01
race_total population_one race_asian,3112.0,0.013749,0.027851,0.000000,0.002954,0.006104,0.013225,4.251072e-01
race_total population_one race_asian_asian indian,3112.0,0.002628,0.007446,0.000000,0.000000,0.000410,0.002318,1.544929e-01
race_total population_one race_asian_chinese,3112.0,0.002644,0.007597,0.000000,0.000000,0.000798,0.002597,2.128881e-01
race_total population_one race_asian_filipino,3112.0,0.002744,0.011772,0.000000,0.000000,0.000981,0.002310,3.490435e-01
race_total population_one race_asian_japanese,3112.0,0.000707,0.003735,0.000000,0.000000,0.000113,0.000689,1.396858e-01
race_total population_one race_asian_korean,3112.0,0.001174,0.002704,0.000000,0.000000,0.000356,0.001313,6.200544e-02
race_total population_one race_asian_vietnamese,3112.0,0.001255,0.003182,0.000000,0.000000,0.000166,0.001267,6.901935e-02
race_total population_one race_asian_other asian,3112.0,0.002598,0.006011,0.000000,0.000000,0.000692,0.002574,1.074529e-01
race_total population_one race_native hawaiian and other pacific islander,3112.0,0.000874,0.004176,0.000000,0.000000,0.000157,0.000666,1.244574e-01
race_total population_one race_native hawaiian and other pacific islander_native hawaiian,3112.0,0.000303,0.002905,0.000000,0.000000,0.000000,0.000140,9.545781e-02
race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro,3112.0,0.000142,0.000512,0.000000,0.000000,0.000000,0.000041,1.071603e-02
race_total population_one race_native hawaiian and other pacific islander_samoan,3112.0,0.000134,0.000738,0.000000,0.000000,0.000000,0.000000,1.895652e-02
race_total population_one race_native hawaiian and other pacific islander_other pacific islander,3112.0,0.000295,0.001343,0.000000,0.000000,0.000000,0.000080,2.813683e-02
race_total population_one race_some other race,3112.0,0.020716,0.038930,0.000000,0.003252,0.008644,0.021647,5.700959e-01
race_total population_two or more races_1,3112.0,0.023941,0.019379,0.000000,0.013370,0.019881,0.028962,2.868743e-01
race_total population_two or more races_white and black or african american,3112.0,0.006444,0.005394,0.000000,0.002642,0.005384,0.009100,6.872038e-02
race_total population_two or more races_white and american indian and alaska native,3112.0,0.008618,0.013071,0.000000,0.002770,0.004888,0.009103,1.496241e-01
race_total population_two or more races_white and asian,3112.0,0.003021,0.003988,0.000000,0.000493,0.002017,0.004108,5.465950e-02
race_total population_two or more races_black or african american and american indian and alaska native,3112.0,0.000652,0.001398,0.000000,0.000000,0.000099,0.000745,1.833862e-02
race alone or in combination with one or more other races_total population,3112.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00
race alone or in combination with one or more other races_total population_white,3112.0,0.852907,0.165090,0.069895,0.797774,0.919974,0.967634,1.000000e+00
race alone or in combination with one or more other races_total population_black or african american,3112.0,0.098875,0.146039,0.000000,0.012197,0.031814,0.116497,8.752193e-01
race alone or in combination with one or more other races_total population_american indian and alaska native,3112.0,0.029923,0.083277,0.000000,0.006616,0.010630,0.020071,9.482386e-01
race alone or in combination with one or more other races_total population_asian,3112.0,0.018213,0.033827,0.000000,0.005151,0.009130,0.018139,6.115702e-01
race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander,3112.0,0.002067,0.010209,0.000000,0.000028,0.000844,0.002026,3.343148e-01
race alone or in combination with one or more other races_total population_some other race,3112.0,0.023626,0.040864,0.000000,0.004593,0.010743,0.025431,5.783582e-01
hispanic or latino and race_total population,3112.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00
hispanic or latino and race_total population_hispanic or latino (of any race),3112.0,0.093201,0.138387,0.000000,0.021164,0.041460,0.096102,9.906877e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_mexican,3112.0,0.069331,0.123512,0.000000,0.011685,0.024515,0.062040,9.561461e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican,3112.0,0.005656,0.013636,0.000000,0.000594,0.002389,0.005221,3.157797e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_cuban,3112.0,0.001568,0.008012,0.000000,0.000000,0.000415,0.001439,3.629896e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino,3112.0,0.016645,0.037029,0.000000,0.003461,0.007472,0.016410,7.569581e-01
hispanic or latino and race_total population_not hispanic or latino,3112.0,0.906799,0.138387,0.009312,0.903898,0.958540,0.978836,1.000000e+00
hispanic or latino and race_total population_not hispanic or latino_white alone,3112.0,0.765065,0.201302,0.007278,0.648714,0.839026,0.926383,1.000000e+00
hispanic or latino and race_total population_not hispanic or latino_black or african american alone,3112.0,0.088817,0.143617,0.000000,0.006417,0.021785,0.098512,8.741228e-01
hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone,3112.0,0.018016,0.074926,0.000000,0.001270,0.002773,0.006721,9.096121e-01
hispanic or latino and race_total population_not hispanic or latino_asian alone,3112.0,0.013534,0.027510,0.000000,0.002878,0.006014,0.012792,4.148463e-01
hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone,3112.0,0.000780,0.003856,0.000000,0.000000,0.000078,0.000566,1.116170e-01
hispanic or latino and race_total population_not hispanic or latino_some other race alone,3112.0,0.001097,0.002298,0.000000,0.000000,0.000429,0.001410,5.483672e-02
hispanic or latino and race_total population_not hispanic or latino_two or more races,3112.0,0.019489,0.016671,0.000000,0.010676,0.016337,0.023087,2.330136e-01
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race,3112.0,0.000433,0.000866,0.000000,0.000000,0.000102,0.000561,1.422370e-02
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race - and three or more races,3112.0,0.019056,0.016572,0.000000,0.010360,0.015859,0.022490,2.323104e-01
total housing units,3112.0,0.490815,0.124623,0.253924,0.424961,0.463786,0.520663,2.017974e+00
citizen - voting age population_citizen - 18 and over population,3112.0,0.750649,0.052831,0.445682,0.731844,0.760126,0.782987,9.074868e-01
citizen - voting age population_citizen - 18 and over population_male,3112.0,0.372103,0.035985,0.217886,0.354513,0.371881,0.388385,7.185417e-01
citizen - voting age population_citizen - 18 and over population_female,3112.0,0.378546,0.032234,0.173038,0.366546,0.385605,0.398996,4.718094e-01
sex and age_total population,3112.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00
sex and age_total population_male,3112.0,0.500776,0.023714,0.413863,0.488908,0.496187,0.505926,7.899605e-01
sex and age_total population_female,3112.0,0.499224,0.023714,0.210039,0.494074,0.503813,0.511092,5.861366e-01
sex and age_total population_sex ratio (males per 100 females),3112.0,100.861054,11.927512,70.600000,95.700000,98.500000,102.400000,3.761000e+02
sex and age_total population_under 5 years,3112.0,0.058274,0.012078,0.009281,0.051144,0.057802,0.064237,1.428571e-01
sex and age_total population_5 to 9 years,3112.0,0.061998,0.012082,0.016174,0.054532,0.061528,0.068665,1.278447e-01
sex and age_total population_10 to 14 years,3112.0,0.064260,0.011850,0.016885,0.057332,0.064139,0.070506,1.483254e-01
sex and age_total population_15 to 19 years,3112.0,0.064699,0.014228,0.009174,0.057430,0.063633,0.069921,2.644163e-01
sex and age_total population_20 to 24 years,3112.0,0.062519,0.024013,0.000000,0.051533,0.058043,0.066097,2.867792e-01
sex and age_total population_25 to 34 years,3112.0,0.117923,0.022631,0.035022,0.104115,0.115488,0.129104,2.538147e-01
sex and age_total population_35 to 44 years,3112.0,0.115818,0.015363,0.045429,0.106848,0.116163,0.124152,1.888218e-01
sex and age_total population_45 to 54 years,3112.0,0.129319,0.014958,0.052870,0.120637,0.130296,0.138600,2.414599e-01
sex and age_total population_55 to 59 years,3112.0,0.072628,0.012142,0.017089,0.065805,0.072305,0.078712,2.017544e-01
sex and age_total population_60 to 64 years,3112.0,0.068983,0.013705,0.015126,0.060558,0.067835,0.075685,1.754144e-01
sex and age_total population_65 to 74 years,3112.0,0.105167,0.025948,0.024984,0.089679,0.102301,0.116763,3.398706e-01
sex and age_total population_75 to 84 years,3112.0,0.055910,0.016874,0.006536,0.045179,0.054350,0.064659,1.735552e-01
sex and age_total population_85 years and over,3112.0,0.022501,0.009228,0.000000,0.016359,0.021085,0.026899,8.502538e-02
sex and age_total population_median age (years),3112.0,0.004116,0.009753,0.000004,0.000577,0.001561,0.003750,2.039474e-01
sex and age_total population_under 18 years,3112.0,0.223623,0.034813,0.073158,0.202954,0.223064,0.241075,4.049768e-01
sex and age_total population_16 years and over,3112.0,0.802455,0.031966,0.632349,0.785884,0.802894,0.821162,9.347515e-01
sex and age_total population_18 years and over,3112.0,0.776377,0.034813,0.595023,0.758925,0.776936,0.797046,9.268424e-01
sex and age_total population_21 years and over,3112.0,0.737593,0.038678,0.543791,0.717017,0.737812,0.760544,9.107265e-01
sex and age_total population_62 years and over,3112.0,0.223854,0.052546,0.054333,0.190519,0.220282,0.251669,6.201456e-01
sex and age_total population_65 years and over,3112.0,0.183579,0.045926,0.037986,0.154466,0.180192,0.208009,5.559633e-01
sex and age_total population_18 years and over_1,3112.0,0.776377,0.034813,0.595023,0.758925,0.776936,0.797046,9.268424e-01
sex and age_total population_18 years and over_male,3112.0,0.386060,0.031319,0.287995,0.369051,0.380786,0.396571,7.237111e-01
sex and age_total population_18 years and over_female,3112.0,0.390317,0.026195,0.174534,0.380086,0.393784,0.405817,4.985799e-01
sex and age_total population_18 years and over_sex ratio (males per 100 females),3112.0,99.632262,14.794030,70.800000,93.200000,96.600000,101.000000,4.147000e+02
sex and age_total population_65 years and over_1,3112.0,0.183579,0.045926,0.037986,0.154466,0.180192,0.208009,5.559633e-01
sex and age_total population_65 years and over_male,3112.0,0.084032,0.023584,0.015325,0.069043,0.081007,0.095678,2.685890e-01
sex and age_total population_65 years and over_female,3112.0,0.099547,0.023556,0.022662,0.085041,0.098869,0.112504,2.873743e-01

In [85]:
# check recoding 
with pd.option_context('display.max_rows', 100, 'display.max_columns', None): 
    display(diabetes_summary.iloc[ : ,[0,1,3,7]]) # select which columns in the summary table we want to present

,count,mean,min,max
Diabetes_Number,3112.0,0.092857,0.019038,2.242079e-01
Obesity_Number,3112.0,0.251666,0.088946,4.767883e-01
Physical_Inactivity_Number,3112.0,0.200861,0.064949,3.922853e-01
sex and age_total population_65 years and over_sex ratio (males per 100 females),3112.0,84.275643,34.700000,2.200000e+02
race_total population,3112.0,103682.624036,228.000000,1.009805e+07
race_total population_one race,3112.0,0.976059,0.713126,1.000000e+00
race_total population_two or more races,3112.0,0.023941,0.000000,2.868743e-01
race_total population_one race_1,3112.0,0.976059,0.713126,1.000000e+00
race_total population_one race_white,3112.0,0.831107,0.038912,1.000000e+00
race_total population_one race_black or african american,3112.0,0.090215,0.000000,8.741228e-01
race_total population_one race_american indian and alaska native,3112.0,0.019398,0.000000,9.247994e-01
race_total population_one race_american indian and alaska native_cherokee tribal grouping,3112.0,0.001791,0.000000,4.096685e-01
race_total population_one race_american indian and alaska native_chippewa tribal grouping,3112.0,0.001338,0.000000,7.264946e-01
race_total population_one race_american indian and alaska native_navajo tribal grouping,3112.0,0.001229,0.000000,7.054752e-01
race_total population_one race_american indian and alaska native_sioux tribal grouping,3112.0,0.003315,0.000000,8.339016e-01
race_total population_one race_asian,3112.0,0.013749,0.000000,4.251072e-01
race_total population_one race_asian_asian indian,3112.0,0.002628,0.000000,1.544929e-01
race_total population_one race_asian_chinese,3112.0,0.002644,0.000000,2.128881e-01
race_total population_one race_asian_filipino,3112.0,0.002744,0.000000,3.490435e-01
race_total population_one race_asian_japanese,3112.0,0.000707,0.000000,1.396858e-01
race_total population_one race_asian_korean,3112.0,0.001174,0.000000,6.200544e-02
race_total population_one race_asian_vietnamese,3112.0,0.001255,0.000000,6.901935e-02
race_total population_one race_asian_other asian,3112.0,0.002598,0.000000,1.074529e-01
race_total population_one race_native hawaiian and other pacific islander,3112.0,0.000874,0.000000,1.244574e-01
race_total population_one race_native hawaiian and other pacific islander_native hawaiian,3112.0,0.000303,0.000000,9.545781e-02
race_total population_one race_native hawaiian and other pacific islander_guamanian or chamorro,3112.0,0.000142,0.000000,1.071603e-02
race_total population_one race_native hawaiian and other pacific islander_samoan,3112.0,0.000134,0.000000,1.895652e-02
race_total population_one race_native hawaiian and other pacific islander_other pacific islander,3112.0,0.000295,0.000000,2.813683e-02
race_total population_one race_some other race,3112.0,0.020716,0.000000,5.700959e-01
race_total population_two or more races_1,3112.0,0.023941,0.000000,2.868743e-01
race_total population_two or more races_white and black or african american,3112.0,0.006444,0.000000,6.872038e-02
race_total population_two or more races_white and american indian and alaska native,3112.0,0.008618,0.000000,1.496241e-01
race_total population_two or more races_white and asian,3112.0,0.003021,0.000000,5.465950e-02
race_total population_two or more races_black or african american and american indian and alaska native,3112.0,0.000652,0.000000,1.833862e-02
race alone or in combination with one or more other races_total population,3112.0,1.000000,1.000000,1.000000e+00
race alone or in combination with one or more other races_total population_white,3112.0,0.852907,0.069895,1.000000e+00
race alone or in combination with one or more other races_total population_black or african american,3112.0,0.098875,0.000000,8.752193e-01
race alone or in combination with one or more other races_total population_american indian and alaska native,3112.0,0.029923,0.000000,9.482386e-01
race alone or in combination with one or more other races_total population_asian,3112.0,0.018213,0.000000,6.115702e-01
race alone or in combination with one or more other races_total population_native hawaiian and other pacific islander,3112.0,0.002067,0.000000,3.343148e-01
race alone or in combination with one or more other races_total population_some other race,3112.0,0.023626,0.000000,5.783582e-01
hispanic or latino and race_total population,3112.0,1.000000,1.000000,1.000000e+00
hispanic or latino and race_total population_hispanic or latino (of any race),3112.0,0.093201,0.000000,9.906877e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_mexican,3112.0,0.069331,0.000000,9.561461e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_puerto rican,3112.0,0.005656,0.000000,3.157797e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_cuban,3112.0,0.001568,0.000000,3.629896e-01
hispanic or latino and race_total population_hispanic or latino (of any race)_other hispanic or latino,3112.0,0.016645,0.000000,7.569581e-01
hispanic or latino and race_total population_not hispanic or latino,3112.0,0.906799,0.009312,1.000000e+00
hispanic or latino and race_total population_not hispanic or latino_white alone,3112.0,0.765065,0.007278,1.000000e+00
hispanic or latino and race_total population_not hispanic or latino_black or african american alone,3112.0,0.088817,0.000000,8.741228e-01
hispanic or latino and race_total population_not hispanic or latino_american indian and alaska native alone,3112.0,0.018016,0.000000,9.096121e-01
hispanic or latino and race_total population_not hispanic or latino_asian alone,3112.0,0.013534,0.000000,4.148463e-01
hispanic or latino and race_total population_not hispanic or latino_native hawaiian and other pacific islander alone,3112.0,0.000780,0.000000,1.116170e-01
hispanic or latino and race_total population_not hispanic or latino_some other race alone,3112.0,0.001097,0.000000,5.483672e-02
hispanic or latino and race_total population_not hispanic or latino_two or more races,3112.0,0.019489,0.000000,2.330136e-01
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races including some other race,3112.0,0.000433,0.000000,1.422370e-02
hispanic or latino and race_total population_not hispanic or latino_two or more races_two races excluding some other race - and three or more races,3112.0,0.019056,0.000000,2.323104e-01
total housing units,3112.0,0.490815,0.253924,2.017974e+00
citizen - voting age population_citizen - 18 and over population,3112.0,0.750649,0.445682,9.074868e-01
citizen - voting age population_citizen - 18 and over population_male,3112.0,0.372103,0.217886,7.185417e-01
citizen - voting age population_citizen - 18 and over population_female,3112.0,0.378546,0.173038,4.718094e-01
sex and age_total population,3112.0,1.000000,1.000000,1.000000e+00
sex and age_total population_male,3112.0,0.500776,0.413863,7.899605e-01
sex and age_total population_female,3112.0,0.499224,0.210039,5.861366e-01
sex and age_total population_sex ratio (males per 100 females),3112.0,100.861054,70.600000,3.761000e+02
sex and age_total population_under 5 years,3112.0,0.058274,0.009281,1.428571e-01
sex and age_total population_5 to 9 years,3112.0,0.061998,0.016174,1.278447e-01
sex and age_total population_10 to 14 years,3112.0,0.064260,0.016885,1.483254e-01
sex and age_total population_15 to 19 years,3112.0,0.064699,0.009174,2.644163e-01
sex and age_total population_20 to 24 years,3112.0,0.062519,0.000000,2.867792e-01
sex and age_total population_25 to 34 years,3112.0,0.117923,0.035022,2.538147e-01
sex and age_total population_35 to 44 years,3112.0,0.115818,0.045429,1.888218e-01
sex and age_total population_45 to 54 years,3112.0,0.129319,0.052870,2.414599e-01
sex and age_total population_55 to 59 years,3112.0,0.072628,0.017089,2.017544e-01
sex and age_total population_60 to 64 years,3112.0,0.068983,0.015126,1.754144e-01
sex and age_total population_65 to 74 years,3112.0,0.105167,0.024984,3.398706e-01
sex and age_total population_75 to 84 years,3112.0,0.055910,0.006536,1.735552e-01
sex and age_total population_85 years and over,3112.0,0.022501,0.000000,8.502538e-02
sex and age_total population_median age (years),3112.0,0.004116,0.000004,2.039474e-01
sex and age_total population_under 18 years,3112.0,0.223623,0.073158,4.049768e-01
sex and age_total population_16 years and over,3112.0,0.802455,0.632349,9.347515e-01
sex and age_total population_18 years and over,3112.0,0.776377,0.595023,9.268424e-01
sex and age_total population_21 years and over,3112.0,0.737593,0.543791,9.107265e-01
sex and age_total population_62 years and over,3112.0,0.223854,0.054333,6.201456e-01
sex and age_total population_65 years and over,3112.0,0.183579,0.037986,5.559633e-01
sex and age_total population_18 years and over_1,3112.0,0.776377,0.595023,9.268424e-01
sex and age_total population_18 years and over_male,3112.0,0.386060,0.287995,7.237111e-01
sex and age_total population_18 years and over_female,3112.0,0.390317,0.174534,4.985799e-01
sex and age_total population_18 years and over_sex ratio (males per 100 females),3112.0,99.632262,70.800000,4.147000e+02
sex and age_total population_65 years and over_1,3112.0,0.183579,0.037986,5.559633e-01
sex and age_total population_65 years and over_male,3112.0,0.084032,0.015325,2.685890e-01
sex and age_total population_65 years and over_female,3112.0,0.099547,0.022662,2.873743e-01

In [101]:
for col in rc_cols:
    condition = (diabetes[col] >= 0) & (diabetes[col] <= .5)
    assert condition.all(), f"Not all values in {col} are bounded by 0 and 1."

AssertionError: Not all values in race_total population_one race are bounded by 0 and 1.

#### d. Check for duplicate columns

There are a lot of columns in this data frame. Let's see if there are any are duplicates.

In [ ]:
# I used Google to figure this out, and adapted this example for our purposes:  
# source: https://thispointer.com/how-to-find-drop-duplicate-columns-in-a-dataframe-python-pandas/ 
def getDuplicateColumns(df):
    '''
    Get a list of duplicate columns.
    It will iterate over all the columns in dataframe and find the columns whose contents are duplicate.
    :param df: Dataframe object
    :return: List of columns whose contents are duplicates.
    '''
    duplicateColumnNames = set()
    # Iterate over all the columns in dataframe
    for x in range(df.shape[1]):
        # Select column at xth index.
        col = df.iloc[:, x]
        # Iterate over all the columns in DataFrame from (x+1)th index till end
        for y in range(x + 1, df.shape[1]):
            # Select column at yth index.
            otherCol = df.iloc[:, y]
            # Check if two columns at x 7 y index are equal
            if col.equals(otherCol):
                duplicateColumnNames.add(df.columns.values[y])
    return list(duplicateColumnNames)

duplicateColumnNames = list(getDuplicateColumns(______))
print('Duplicate Columns are as follows: ')
duplicateColumnNames

In [ ]:
# now drop list of duplicate features from our df using the .drop() method
diabetes = diabetes.drop(columns=______)

## 2. Exploratory Data Analysis

In [ ]:
# insert your EDAs and interpretations in this section

## 3. Prepare to Fit Models

### 3.1 Finalize Data Set

We've already cleaned up the data, but we can make a few more adjustments before partitioning the data and training models. Let's recode 'State' to be a categorical variable using `pd.get_dummies` and drop 'County' using `.drop()` because 'CountyFIPS' is already a unique identifier for the county.

In [ ]:
# create dummy features out of 'State' , which might be related to diabetes rates 
diabetes_clean = pd.get_dummies(______, 
                               columns = [______],  
                               drop_first = True) # only create 49 dummies by dropping first in category

# drop 'County' variable
diabetes_clean = diabetes_clean.drop(labels = ['County'],
                               axis = ______) # which axis tells python we want to drop columns rather than index rows?

# look at first 10 rows of new data frame 
diabetes_clean.______

### 3.2/3.3 Partition Data and Feature Selection

Now, we will partition our data to prepare it for the training process. We will use 60% train—20% validation—20% test in this case. More data in the training set lowers bias, but then increases variance in the validation/test sets. Balancing between bias and variance with choice of these set sizes is important as we want to ensure that there is enough data to train on to get good predictions, but also want to make sure our hold-out sets are representative enough.

In [ ]:
from sklearn.model_selection import train_test_split

# Set y 
y = ______

# X (everything except diabetes, our target)
X = ______

We should also preprocess our data. Using the `preprocessing` module from sklearn, let's scale our features so that they are mean-centered.

In [ ]:
from sklearn import preprocessing

X = preprocessing.scale(X)

We can also get rid of the 0 variance features using the `VarianceThreshold()` method from `feature_selection`.

In [ ]:
from sklearn import feature_selection

selector = feature_selection.VarianceThreshold(0)
X = selector.fit_transform(X)

And finally, let's split our data:

In [ ]:
# split the data
# train_test_split returns 4 values: X_train, X_test, y_train, y_test, so how do we create a 60-20-20 train-validate-test split? 

X_train, X_test, y_train, y_test = ______

X_train, X_validate, y_train, y_validate = ______

## 4. Train Models

In [ ]:
# train your five models in this section

## 5. Validate and Refine Models

In [ ]:
# use X_validation and y_validation data sets to evaluate and refine your models

## 6. Discussion Questions

In [1]:
# insert responses for discussion Qs here